app_root/blueprints/auth.py
from itsdangerous.exc import SignatureExpired, BadTimeSignature, BadSignature

from flask import Blueprint, render_template, redirect, url_for, flash, current_app
from flask_login import login_user, logout_user, login_required, current_user

from ..extensions import db, cryptman
from ..constants import *
from .. import exceptions as excs

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    # > when user is already logged in, don't allow him to login again !
    if current_user.is_authenticated:
        flash('You are already logged in.', 'secondary')
        return redirect(url_for('views.home'))

    from ..forms import LoginForm
    from ..models import DatabaseSimpleAPI
    login_form = LoginForm()

    if login_form.validate_on_submit():
        try:
            # > try fetching the user, if anything wrong, error will be raised
            user = DatabaseSimpleAPI().check_user_login(login_form.username.data, login_form.password.data)
        except excs.UserNotFoundError as ex:  # the ex.message contains the error message and u can get it with str(ex)
            login_form.username.errors.append(str(ex))
        except excs.InCorrectPasswordError as ex:
            login_form.password.errors.append(str(ex))
        else:
            # > when the user was fetched with no error
            login_user(user, login_form.remember.data)  # login it with his choice to remember or not
            flash(f'Welcome back {user.username}', 'success')  # welcome him on the web page
            current_app.logger.info(f'Done: User @{user.username} logged in.')  # log for debugging
            return redirect(url_for('views.notes'))  # go to notes page

    return render_template('pages/login.html', login_form=login_form)


@auth.route('/signup', methods=['GET', 'POST'])
def register():
    # > when user is already logged in, don't allow him to login again !
    if current_user.is_authenticated:
        flash('You can not register while logged in.', 'secondary')
        return redirect(url_for('views.home'))

    from ..forms import RegisterForm
    from ..models import DatabaseSimpleAPI
    register_form = RegisterForm()

    if register_form.validate_on_submit():
        try:
            # > try to create new user and saving it into database automatically, if anything goes wrong, error will be raised
            user = DatabaseSimpleAPI().add_user(register_form.username.data, register_form.password.data, autosave=True)
            # < if the execution reached here, that means the used creation succeeded
            current_app.logger.info(f'Done: New User Registered ({register_form.username.data}).')  # log for debugging
        # > I take the exceptions separately just to know where to put the error message (username field or password field) to get shown on the web page later
        except (excs.UsernameAlreadyExistError, excs.UsernamePatternError) as ex:
            register_form.username.errors.append(str(ex))
        except excs.WeakPasswordError as ex:
            register_form.password.errors.append(str(ex))
        else:
            # > flash a success message and go to log-in,
            # > this code can be put up inside the try statement, no difference ¯\_(ツ)_/¯
            flash('You Registered Successfully, Please login.', 'success')
            return redirect(url_for('auth.login'))

    return render_template('pages/register.html', register_form=register_form)


@auth.route('/logout/<string:token>')
@login_required
def logout(token: str):
    """ logout the user after checking the logout token """
    try:
        # > get expiration date for the token (in seconds)
        token_max_age = current_app.config.get(StringNames.LOGOUT_TOKEN_EXPIRE_SECONDS, 3600)
        # > next line deserializes the token with checking its timestamp using app config LOGOUT_TOKEN_EXPIRE_SECONDS
        plaintext = cryptman.serial_decrypt(current_user.username, token, token_max_age)
    except SignatureExpired as ex:
        # | when timestamp is invalid
        flash('Your Logout token is expired, Please try again.', 'warning')
        return redirect(url_for('views.home'))
    except (BadSignature, BadTimeSignature) as ex:
        # | when token is broken, or it's not even a token
        flash('Your try to Logout failed, Please try again.', 'warning')
        return redirect(url_for('views.home'))

    # - so far, token is valid, next lets check if it's a logout token or something else

    if plaintext != StringNames.LOGOUT_TOKEN_NAME:
        # | when token is valid but not for logging out :/
        current_app.logger.warning(f'WARNING: logout endpoint received a valid text("{plaintext}") as token !')  # log for future debugging
        flash('Your try to Logout failed badly, Please try again.', 'error')
        return redirect(url_for('views.home'))

    # > now, we've checked everything, lets logout :)
    logout_user()
    return redirect(url_for('auth.login'))

app_root/blueprints/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, current_app
from flask_login import current_user, login_required

from .. import exceptions as excs
from ..constants import *

views = Blueprint('views', __name__)


@views.get('/')
def home():
    return render_template('pages/index.html')


@views.get('/notes')
@login_required
def notes():
    from ..models import NoteModel
    # > get all notes ordered by last modified and created date (simple, we can do more but things will get complicated)
    user_notes = current_user.notes.order_by(NoteModel.last_modified.desc(), NoteModel.create_date.desc()).all()
    oldest_note = user_notes[-1] if user_notes else None  # get the oldest note of current user if there are any
    return render_template('pages/notes.html', notes=user_notes, oldest_note=oldest_note)


@views.route('/create_note', methods=['GET', 'POST'])
@login_required
def create_note():
    from ..forms import NoteForm
    from ..models import DatabaseSimpleAPI
    note_form = NoteForm()

    if note_form.validate_on_submit():
        dsi = DatabaseSimpleAPI()
        try:
            # > try to add the note directly
            note = dsi.add_note(note_form.title.data, note_form.content.data, current_user, True)
        except excs.NottyException as ex:  # when any error happen within the known app errors
            flash(str(ex), 'danger')  # flash the error message
        else:
            # when success
            flash('Your Note was created successfully', 'success')
            current_app.logger.info(f'Done: Note #{note.id} created by @{current_user.username}')  # log for debugging
            return redirect(url_for('views.notes'))

    return render_template('pages/create_note.html', note_form=note_form)


@views.get('/note/<string:token>')
@login_required
def view_note(token: str):
    from ..models import DatabaseSimpleAPI
    note = DatabaseSimpleAPI().get_note(token)  # get note by its token
    if not note:
        return abort(SCodes.NOT_FOUND_404)  # when no note was found, 404

    # > check if the note owner is the same as logged in
    if note.user != current_user:
        flash('You do not have the privileges to view this Note!', 'danger')
        current_app.logger.warning(f'WARNING: user @{current_user.username} tried to access other\'s note #{note.id}')  # log for debugging
        return redirect(url_for('views.notes'))
    return render_template('pages/view_note.html', note=note)


@views.get('/about')
def about():
    return render_template('pages/about.html')

app_root/templates/pages/about.html
{% extends "roots/base.html" %}


{% block content %}
    <h1 class="text-primary">About</h1>
    <h2>about content</h2>
{% endblock content %}

app_root/templates/pages/create_note.html
{% extends "roots/base.html" %}



{% block head %}
    {# This external sources are for WYSIWYG editor #}
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
{% endblock head %}



{% block content %}
    <div class="col-12 col-lg-10 col-xl-8 mx-auto my-5">
        <h1 class="text-primary">Create New Note</h1>
        <form action="{{ url_for('views.create_note') }}" method="POST">
            {{ note_form.hidden_tag() }}

            <div class="my-4">
                {{ note_form.title.label(class='form-label') }}
                {{ note_form.title(class='form-control' + (' is-invalid' if note_form.title.errors else ''), placeholder='Note Title')}}
                {% for error in note_form.title.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="my-4">
                {{ note_form.content.label(class='form-label') }}
                {{ note_form.content(id='x', hidden=True, class='form-control' + (' is-invalid' if note_form.content.errors else '')) }}
                <trix-editor input="x" placeholder="Note Content"></trix-editor>
                {% for error in note_form.content.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>

            {{ note_form.submit(class='btn btn-primary px-5') }}
        </form>
    </div>
{% endblock content %}

app_root/templates/pages/index.html
{% extends "roots/base.html" %}


{% block content %}

    {# The header #}
    <div class="px-4 py-5 my-5 text-center">
        <img class="d-block mx-auto mb-4" alt="logo" src="{{ url_for('static', filename='img/icons/note.png') }}">
        <h1 class="display-5 fw-bold text-success text-secondary">You Made it !</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">
                Welcome to <b class="text-primary">Notty</b> – your simple, open-source notes app built with Flask! Designed for productivity enthusiasts,
                <b class="text-primary">Notty</b> offers a seamless multiuser experience, Join our community today and start simplifying your life, one note at a time.
            </p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Primary button</button>
                <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button>
            </div>
        </div>
    </div>
    {# End of header #}

    {# The features section #}
    <div class="container px-4 py-5" id="icon-grid">
        <h2 class="pb-2 border-bottom text-success">Features</h2>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5">
            <div class="col d-flex align-items-start">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em">
                    <use xlink:href="#bootstrap"></use>
                </svg>
                <div>
                    <h3 class="fw-bold mb-0 fs-4 text-secondary">No Bloat !</h3>
                    <p>Allows you to Create, View, Edit and Delete your notes, nothing else.</p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em">
                    <use xlink:href="#cpu-fill"></use>
                </svg>
                <div>
                    <h3 class="fw-bold mb-0 fs-4 text-secondary">No Spyware</h3>
                    <p>This website wasn't made by neither Microshaft nor Google, or even the Zuck.</p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em">
                    <use xlink:href="#calendar3"></use>
                </svg>
                <div>
                    <h3 class="fw-bold mb-0 fs-4 text-secondary">Open Source</h3>
                    <p>You can View, Edit, Redistribute the whole thing !</p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em">
                    <use xlink:href="#home"></use>
                </svg>
                <div>
                    <h3 class="fw-bold mb-0 fs-4 text-secondary">Free of Cost</h3>
                    <p>This website also wasn't made by IApple (I stands for Idiot :).</p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em">
                    <use xlink:href="#geo-fill"></use>
                </svg>
                <div>
                    <h3 class="fw-bold mb-0 fs-4 text-secondary">No ads</h3>
                    <p>The World Wide Web is becoming more silly by each Ad published on it.</p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em">
                    <use xlink:href="#speedometer2"></use>
                </svg>
                <div>
                    <h3 class="fw-bold mb-0 fs-4 text-secondary">Built with Flask</h3>
                    <p>Flask is one of the best micro web frameworks, and has a lot of audience.</p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em">
                    <use xlink:href="#toggles2"></use>
                </svg>
                <div>
                    <h3 class="fw-bold mb-0 fs-4 text-secondary">Educational Purposes</h3>
                    <p>You can learn a thing or two from Reading through the source code.</p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em">
                    <use xlink:href="#tools"></use>
                </svg>
                <div>
                    <h3 class="fw-bold mb-0 fs-4 text-secondary">Pull-Welcome</h3>
                    <p>We Welcome Pull requests, and Issues, and Stars on GitHub why not :).</p>
                </div>
            </div>
        </div>
    </div>
    {# End of features section #}

{% endblock content %}

app_root/templates/pages/login.html
{% extends "roots/base.html" %}


{% block content %}
    <div class="mx-auto col-6 my-5">
        <h1 class="text-primary">Login</h1>

        <form action="{{ url_for('auth.login') }}" method="POST">
            {{ login_form.hidden_tag() }}
            <div class="my-4">
                {{ login_form.username.label(class='form-label') }}
                {{ login_form.username(class='form-control' + (' is-invalid' if login_form.username.errors else '')) }}
                {% for error in login_form.username.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="my-4">
                {{ login_form.password.label(class='form-label') }}
                {{ login_form.password(class='form-control' + (' is-invalid' if login_form.password.errors else '')) }}
                {% for error in login_form.password.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="form-check my-4">
                {{ login_form.remember(class='form-check-input cursor-pointer') }}
                {{ login_form.remember.label(class='form-check-label cursor-pointer') }}
            </div>

            {{ login_form.submit(class='btn btn-primary px-5') }}

        </form>
    </div>

{% endblock content %}

app_root/templates/pages/notes.html
{% extends "roots/base.html" %}


{% macro note_card(note) %}
    {# The Note Card, you pass a NoteModel, this macro does the rest to show it on webpage #}
    <div class="col-sm-12 col-lg-6 col-xl-4">
        <div id="note-{{ note.token }}" class="card shadow">
            <h5 class="card-header">
                {% if note.last_modified %}
                    {{ note.last_modified.strftime(DTFORMATS.SHORT) }}
                {% else %}
                    {{ note.create_date.strftime(DTFORMATS.SHORT) }}
                {% endif %}
            </h5>
            <div class="card-body">
                <h3 class="card-title">{{ note.title }}</h3>
                <a href="{{ url_for('views.view_note', token=note.token) }}" class="btn btn-outline-primary px-4 mt-3">View</a>
            </div>
        </div>
    </div>
{% endmacro %}


{% block content %}
    <div class="my-4">
        <h1 class="text-primary">Your Notes</h1>
        {% if notes %}  {# when the user has notes, show them #}

            <div class="row g-4 mt-2">

                {# this is the default top left card #}
                <div class="col-sm-12 col-lg-6 col-xl-4">
                    <div class="card shadow-sm bg-secondary">
                        <h5 class="card-header text-white">
                            <i>oldest note:</i> {{ oldest_note.create_date.strftime(DTFORMATS.SHORT) }}
                        </h5>
                        <div class="card-body bg-light">
                            <h3 class="card-title">Total notes: {{ notes | length }}</h3>
                            <a href="{{ url_for('views.create_note') }}" class="btn btn-outline-primary px-4 mt-3">Create New</a>
                        </div>
                    </div>
                </div>


                {% for note in notes %}
                    {{ note_card(note) }}
                {% endfor %}
            </div>

        {% else %}  {# when the user has no notes, show the following #}

            <div class="col-8 mx-auto my-5 p-4 shadow opacity-75 bg-light rounded-2 border border-1 border-secondary text-center">
                <div class="lead fw-bold text-secondary p-5">
                    No Notes was found for this user.
                </div>
                <div class="pb-5">
                    <a href="{{ url_for('views.create_note') }}" class="px-5 btn btn-primary">Create</a>
                </div>
            </div>

        {% endif %}
    </div>
{% endblock content %}

app_root/templates/pages/register.html
{% extends "roots/base.html" %}



{% block content %}
    <div class="mx-auto col-6 my-5">
        <h1 class="text-primary">Register</h1>
        <form action="{{ url_for('auth.register') }}" method="POST">
            {{ register_form.hidden_tag() }}

            <div class="my-4">
                {{ register_form.username.label(class='form-label') }}
                {{ register_form.username(class='form-control' + (' is-invalid' if register_form.username.errors else ''), placeholder='Choose a Username') }}
                {% for error in register_form.username.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="my-4">
                {{ register_form.password.label(class='form-label') }}
                {{ register_form.password(class='form-control' + (' is-invalid' if register_form.password.errors else ''), placeholder='Choose a Password') }}
                {% for error in register_form.password.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="my-4">
                {{ register_form.confirm_password.label(class='form-label') }}
                {{ register_form.confirm_password(class='form-control' + (' is-invalid' if register_form.confirm_password.errors else ''), placeholder='Re Enter Your chosen password') }}
                {% for error in register_form.confirm_password.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="form-check my-4">
                {{ register_form.agreement(class='form-check-input cursor-pointer') }}
                {{ register_form.agreement.label(class='form-check-label cursor-pointer') }}
            </div>

            {{ register_form.submit(class='btn btn-primary px-5') }}

        </form>
    </div>
{% endblock content %}

app_root/templates/pages/view_note.html
{% extends "roots/base.html" %}

{% block content %}
    <div class="my-5">

        <div>
            <div class="my-0 small">Created at {{ note.create_date.strftime(DTFORMATS.SHORT) }},
                {{ 'Never modified' if not note.last_modified else 'Last modified ' + note.last_modified.strftime(DTFORMATS.SHORT) }}</div>
            <h1>{{ note.title }}</h1>
        </div>

        <hr>

        <div>
            {{ note.content | safe }}
        </div>
    </div>
{% endblock content %}