app_root/blueprints/auth.py
from itsdangerous.exc import SignatureExpired, BadTimeSignature, BadSignature

from flask import Blueprint, render_template, redirect, url_for, flash, current_app
from flask_login import login_user, logout_user, login_required, current_user

from ..extensions import db, cryptman
from ..constants import *
from .. import exceptions as excs

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    # > when user is already logged in, don't allow him to login again !
    if current_user.is_authenticated:
        flash('You are already logged in.', 'secondary')
        return redirect(url_for('views.home'))

    from ..forms import LoginForm
    from ..models import DatabaseSimpleAPI
    login_form = LoginForm()

    if login_form.validate_on_submit():
        try:
            # > try fetching the user, if anything wrong, error will be raised
            user = DatabaseSimpleAPI().check_user_login(login_form.username.data, login_form.password.data)
        except excs.UserNotFoundError as ex:  # the ex.message contains the error message and u can get it with str(ex)
            login_form.username.errors.append(str(ex))
        except excs.InCorrectPasswordError as ex:
            login_form.password.errors.append(str(ex))
        else:
            # > when the user was fetched with no error
            login_user(user, login_form.remember.data)  # login it with his choice to remember or not
            flash(f'Welcome back {user.username}', 'success')  # welcome him on the web page
            current_app.logger.info(f'Done: User @{user.username} logged in.')  # log for debugging
            return redirect(url_for('views.notes'))  # go to notes page

    return render_template('pages/login.html', login_form=login_form)


@auth.route('/signup', methods=['GET', 'POST'])
def register():
    # > when user is already logged in, don't allow him to login again !
    if current_user.is_authenticated:
        flash('You can not register while logged in.', 'secondary')
        return redirect(url_for('views.home'))

    from ..forms import RegisterForm
    from ..models import DatabaseSimpleAPI
    register_form = RegisterForm()

    if register_form.validate_on_submit():
        try:
            # > try to create new user and saving it into database automatically, if anything goes wrong, error will be raised
            user = DatabaseSimpleAPI().add_user(register_form.username.data, register_form.password.data, autosave=True)
            # < if the execution reached here, that means the used creation succeeded
            current_app.logger.info(f'Done: New User Registered ({register_form.username.data}).')  # log for debugging
        # > I take the exceptions separately just to know where to put the error message (username field or password field) to get shown on the web page later
        except (excs.UsernameAlreadyExistError, excs.UsernamePatternError) as ex:
            register_form.username.errors.append(str(ex))
        except excs.WeakPasswordError as ex:
            register_form.password.errors.append(str(ex))
        else:
            # > flash a success message and go to log-in,
            # > this code can be put up inside the try statement, no difference ¯\_(ツ)_/¯
            flash('You Registered Successfully, Please login.', 'success')
            return redirect(url_for('auth.login'))

    return render_template('pages/register.html', register_form=register_form)


@auth.route('/logout/<string:token>')
@login_required
def logout(token: str):
    """ logout the user after checking the logout token """
    try:
        # > get expiration date for the token (in seconds)
        token_max_age = current_app.config.get(StringNames.LOGOUT_TOKEN_EXPIRE_SECONDS, 3600)
        # > next line deserializes the token with checking its timestamp using app config LOGOUT_TOKEN_EXPIRE_SECONDS
        plaintext = cryptman.serial_decrypt(current_user.username, token, token_max_age)
    except SignatureExpired as ex:
        # | when timestamp is invalid
        flash('Your Logout token is expired, Please try again.', 'warning')
        return redirect(url_for('views.home'))
    except (BadSignature, BadTimeSignature) as ex:
        # | when token is broken, or it's not even a token
        flash('Your try to Logout failed, Please try again.', 'warning')
        return redirect(url_for('views.home'))

    # - so far, token is valid, next lets check if it's a logout token or something else

    if plaintext != StringNames.LOGOUT_TOKEN_NAME:
        # | when token is valid but not for logging out :/
        current_app.logger.warning(f'WARNING: logout endpoint received a valid text("{plaintext}") as token !')  # log for future debugging
        flash('Your try to Logout failed badly, Please try again.', 'error')
        return redirect(url_for('views.home'))

    # > now, we've checked everything, lets logout :)
    logout_user()
    return redirect(url_for('auth.login'))

app_root/blueprints/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, current_app
from flask_login import current_user, login_required

from .. import exceptions as excs
from ..constants import *

views = Blueprint('views', __name__)


@views.get('/')
def home():
    return render_template('pages/index.html')


@views.get('/notes')
@login_required
def notes():
    from ..models import NoteModel
    # > get all notes ordered by last modified and created date (simple, we can do more but things will get complicated)
    user_notes = current_user.notes.order_by(NoteModel.last_modified.desc(), NoteModel.create_date.desc()).all()
    oldest_note = user_notes[-1] if user_notes else None  # get the oldest note of current user if there are any
    return render_template('pages/notes.html', notes=user_notes, oldest_note=oldest_note)


@views.route('/create_note', methods=['GET', 'POST'])
@login_required
def create_note():
    from ..forms import NoteForm
    from ..models import DatabaseSimpleAPI
    note_form = NoteForm()

    if note_form.validate_on_submit():
        dsi = DatabaseSimpleAPI()
        try:
            # > try to add the note directly
            note = dsi.add_note(note_form.title.data, note_form.content.data, current_user, True)
        except excs.NottyException as ex:  # when any error happen within the known app errors
            flash(str(ex), 'danger')  # flash the error message
        else:
            # when success
            flash('Your Note was created successfully', 'success')
            current_app.logger.info(f'Done: Note #{note.id} created by @{current_user.username}')  # log for debugging
            return redirect(url_for('views.notes'))

    return render_template('pages/create_note.html', note_form=note_form)


@views.get('/note/<string:token>')
@login_required
def view_note(token: str):
    from ..models import DatabaseSimpleAPI
    note = DatabaseSimpleAPI().get_note(token)  # get note by its token
    if not note:
        return abort(SCodes.NOT_FOUND_404)  # when no note was found, 404

    # > check if the note owner is the same as logged in
    if note.user != current_user:
        flash('You do not have the privileges to view this Note!', 'danger')
        current_app.logger.warning(f'WARNING: user @{current_user.username} tried to access other\'s note #{note.id}')  # log for debugging
        return redirect(url_for('views.notes'))
    return render_template('pages/view_note.html', note=note)


@views.get('/about')
def about():
    return render_template('pages/about.html')

app_root/templates/components/flashes.htm
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        <div id="flashes" class="container my-3">
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show shadow-sm" role="alert">
                    {{ message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}

app_root/templates/components/navbar.htm
{#
Simple bootstrap navbar with two Menus and a center Username
#}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">

        {# Brand name and logo #}
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='img/icons/note.png') }}" alt="Logo" height="24" class="d-inline-block align-text-top">
            Notty
        </a>

        {# Integration for mobile view, I hate mobiles #}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">

            {# Fixed nav menu at the left #}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.home') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.notes') }}">Notes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.about') }}">About</a>
                </li>
            </ul>

            {# Centered Username only if the user is logged in #}
            <span class="mx-auto text-white text-uppercase fw-bold">{{ current_user.username }}</span>

            {# Variant right nav menu for register, login, logout, help #}
            <ul class="navbar-nav ms-auto">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout', token=logout_token()) }}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                {% endif %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Help
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark">
                        <li><a class="dropdown-item" href="https://t.me/elhasnaouymed" target="_blank">Contact</a></li>
                        <li><a class="dropdown-item" href="https://github.com/elhasnaouymed" target="_blank">Github</a></li>
                    </ul>
                </li>
            </ul>

        </div>
    </div>
</nav>